# Generated by Django 3.1rc1 on 2020-08-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_song_fav_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_fav_url',
            field=models.CharField(default='http:/i.imgur.com/b9b13Rd.png', max_length=500),
        ),
    ]
