# Generated by Django 3.1rc1 on 2020-08-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200814_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('marks', models.CharField(max_length=500)),
            ],
        ),
    ]
