# Generated by Django 3.1rc1 on 2020-08-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20200827_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
