# Generated by Django 3.1rc1 on 2020-08-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_employeesdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesdata',
            name='date_of_birth',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeesdata',
            name='department_id',
            field=models.IntegerField(default=1),
        ),
    ]
