# Generated by Django 3.1rc1 on 2020-08-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20200828_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesdata',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employeesdata',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeesdata',
            name='last_update_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeesdata',
            name='last_updated_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employeesdata',
            name='email_id',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeesdata',
            name='first_name',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeesdata',
            name='last_name',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='employeesdata',
            name='middle_name',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
