# Generated by Django 3.1rc1 on 2020-08-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20200828_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesdata',
            name='creation_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employeesdata',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employeesdata',
            name='department_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employeesdata',
            name='last_update_date',
            field=models.DateField(blank=True),
        ),
    ]
