# Generated by Django 3.1rc1 on 2020-08-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20200828_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesdata',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeesdata',
            name='last_update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
