# Generated by Django 3.1rc1 on 2020-08-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20200828_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesdata',
            name='image_url',
            field=models.CharField(default='1.JPG', max_length=100),
        ),
    ]
