# Generated by Django 3.1rc1 on 2020-09-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_employeesdata_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absencedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.IntegerField(blank=True)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
            ],
            options={
                'db_table': 'person_absence_details',
            },
        ),
        migrations.CreateModel(
            name='Attachmentsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField(blank=True)),
                ('attachment_type', models.CharField(default='a', max_length=100)),
                ('file_name', models.CharField(default='a', max_length=100)),
                ('file_extension', models.CharField(default='a', max_length=100)),
                ('is_deleted', models.CharField(default='a', max_length=100)),
            ],
            options={
                'db_table': 'transaction_attachment_details',
            },
        ),
    ]
